### ISSUE TITLE
Adding rice and fennel to your vis

### ISSUE THREAD

**Issue by jgarte** [Gavinok/dotneovim#1]
Hi Gavin,

I saw you were asking about `fennel` and `vis` on the fennel matrix channel a few days ago.

Here's the start of my vis config that I've been hacking on for the past few days:

https://git.sr.ht/~jgart/dotfiles/tree/master/item/private_dot_config/vis/config.fnl

technomancy wrote the `subscribe` function. See the [commit message](https://git.sr.ht/~jgart/dotfiles/commit/55c816c6c52a52b39b7354f982716b6de65684c4) I added for more details.

I added an entry in the vis [Tips and Tricks](https://github.com/martanne/vis/wiki/Tips-and-Tricks#how-can-i-use-fennel-to-configure-vis) section that shows how to set it up:

There's one bug at the moment with it.

It works if you're in `~/.config/vis/` but once you `cd` elsewhere it fails to find the fennel config :)

Any help on that bug is much appreciated and feel free to use the config code as you wish.

I'd love to see what you do with the [vis lua API](https://martanne.github.io/vis/doc/) and fennel.

**Comment by Gavinok** [comment]
Wow thanks for going out of your way to reach out!

**Comment by jgarte** [comment]
No prob. 

Here's another idea for hacking the config on vis with idris2:

https://github.com/Russoul/Idris2-Lua/issues/8

Someone tried something with neovim and idris already mentioned in that thread.
